language: ruby

install: gem install jekyll

script: jekyll build --destination blog_folder/

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    target_branch: master
    # github_url: adharshkamath.github.io/example-site/blog
    on:
      branch: master
