sudo: false
language: ruby
cache: bundler
install: 
  - gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)" 
  - gem update --system
  - bundle install 
script:
  - bundle exec jekyll build --destination blog_new/  
  - bundle exec jekyll build
  - rm -rf blog_new
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: dev
env:
  global:
    secure: fFuMX7BU9ZKAdDOQsNDcAowuqlV+JRLEV+R6NRUm0gNiJLcOsOIUIQOudZEAiC4gFP6WAL2YnFnmVsXhjW+j+YopKrVMYZ7+ieQOPadSlEdNTsJiYHN5dFDLAe0na7l1e0mjC54E1lyTT3T1jubnZ4iXc5csgqsjLaVzVpiqkxvRgVT+OLTZE7aiRAk7HWp2qhW7luaUVhomiRb2rHaK0O4DgPDajL4VuAvAq++nFH9u/fP0TxnfO46oTSNhiEafPYDzgCV07pkS6EimAbE9F+q5TI4zUI+dk1aQjkzwzy/cQmNjjAh4ZJSgS4GmOZ9UCuGbYFkuvpuXnlOXcqOuXHkJKYnBoTHlBbvabSuog5se4bCD81idBO3f4h7j1EIYWKBqT9EqKG/l7huuZRmma/cetASveCVV7zjh02J9kWGMovVNno7MQ4i6aPGIQBESu/2msvb7OAHYbEV+LlQCqd3ZFfSl/r0sVmUckXlaTw8y9YukTGxqq5xwfkaC0N7ONI0GShXDhTi36oVmGwRWjpMkBrrv3a01vNdFJZ5mu+Ha0n881O0L6SLENI8S/Lx6WZbXU+0um4UF46acNdpOHfhgh00V1TtFqZbQMS9aRk1RUUMwJx90npjxNCPNcbG6XiDIzKQPTDrdd5I/OPnV5DNjZxi0JlT6uUzKMhPnfE4=
